### ISSUE TITLE
Idea about generation of onvifgen folder

### ISSUE THREAD

**Issue by ahasan016** [kazimierczak-robert/LeonCam#1]
Hello,
I have been using your repository for a similar problem. But I don't want to use Qt and I don't need a database or something. I have simply added all the folders you have in my solution folder and linked them as additional include directory and additional include library from visual studio. But I have a problem with the "wsseapi.h" as it shows me few errors. 
Then I have so far understood that it is either because of the openssl library or I will have to generate onvifgen folder by myself. 
Actually, I have never worked with gsoap or onvif before. So, It would be great if you could help me.

1. Do I have to generate my own gsoap runtime folder?

2. Do I have to generate my own onvifgen folder?
3. Can I simply copy all your folders in my visual studio project, include them from solution properties and use my own main.cpp to call classes defined in your "onvifclientdevice.hpp"?
3. I have seen in the  "wsseapi.h" that it is written in the comment beside #include "soapH.h"	/* replace with soapcpp2-generated *H.h file */. What should I do here?

**Comment by gradzka** [comment]
Hi, we are very pleased that you are based on our **LeonCam**. It is an old project and several points need to be improved. Unfortunately, we do not develop further in the technologies used in **LeonCam** but we are transferring this app to new - **LeonCam2** (`.NET`, `React`). I will try to answer the questions.
1.-2. No. In our project folders were copied, but libraries should be downloaded and attached to solutions (please visit https://github.com/linkingvision/rapidonvif/ and links in **LeonCam** `README` `Attributions`)
3. Yes
4. Try to replace it with `#include "onvifgen/soapH.h"` (linking errors).

We keep our fingers crossed for you!

**Comment by ahasan016** [comment]
@gradzka After a few try, I could finally run the code without debugging error but the program stops at soap initialization. 
As you have worked with it before, any idea what can be the error? please check the images of error : 
![error_log](https://user-images.githubusercontent.com/11074869/88567365-ad731300-d037-11ea-9b8c-8f44523ba00d.JPG)

And my main function is pretty simple. Just uses ip address, user name and password for an onvif camera to create a profile. like in the following image. 
![source_code](https://user-images.githubusercontent.com/11074869/88567503-df847500-d037-11ea-9b5d-dbaaa7eb300f.JPG)

using the onvif manager I can log in using username ="root"
and password = aMjizb75.z@
and the onvif manager gives me the ip addess as follows :
![onvif_ip](https://user-images.githubusercontent.com/11074869/88569210-65a1bb00-d03a-11ea-9c42-2d00d977f2ef.JPG)

**Comment by gradzka** [comment]
Hi, 
* At first glance your string concatenation is wrong, you should have `http+ipaddress+device_service`. Check it!
* On the other hand IP address `169.254.232.159` looks suspiciously. Please check problems with `169.254.x.x` (some addresses that indicate a problem with your connection). Make sure that the device on which you run the program is on the same network as the camera.

**Comment by ahasan016** [comment]
> Hi,
> 
> * At first glance your string concatenation is wrong, you should have `http+ipaddress+device_service`. Check it!
> * On the other hand IP address `169.254.232.159` looks suspiciously. Please check problems with `169.254.x.x` (some addresses that indicate a problem with your connection). Make sure that the device on which you run the program is on the same network as the camera.

Thanks for finding the silly mistake. I have corrected it but it is still showing the same error. 
I have basically no clue with the IP thing. I have directly copied it from the onvif manager. as you can see in the previous comment of onvif manager screenshot. Another thing is that the camera is actually connected to my pc via ethernet cable. Is it a problem? I mean I don't really know much about these networking things either.

**Comment by gradzka** [comment]
We haven't configure connection and test it like you. Our configuration was:
* Plug camera via Wi-Fi/Ethernet cable to local network.
* Plug laptop/computer via Wi-Fi/Ethernet to local network.
* Make sure they see each other. In laptop/computer ping camera. (In Windows: `cmd` console > `ping ip_address`)
* Read also [connect ip camera](https://www.cctvcameraworld.com/connect-ip-camera-computer/) and [problem IP addresses](https://kb.iu.edu/d/aoyj).
* If you want to control camera without `ONVIF` see [FaceRecognitionSystem](https://github.com/gradzka/FaceRecognitionSystem) (file [Camera.cpp](https://github.com/gradzka/FaceRecognitionSystem/blob/master/FaceRecognitionSystem/FaceRecognitionSystem/Camera.cpp)  `sendMessage(char command)` procedure). It uses `CURL` to communication.

**Comment by ahasan016** [comment]
> We haven't configure connection and test it like you. Our configuration was:
> 
> * Plug camera via Wi-Fi/Ethernet cable to local network.
> * Plug laptop/computer via Wi-Fi/Ethernet to local network.
> * Make sure they see each other. In laptop/computer ping camera. (In Windows: `cmd` console > `ping ip_address`)
> * Read also [connect ip camera](https://www.cctvcameraworld.com/connect-ip-camera-computer/) and [problem IP addresses](https://kb.iu.edu/d/aoyj).
> * If you want to control camera without `ONVIF` see [FaceRecognitionSystem](https://github.com/gradzka/FaceRecognitionSystem) (file [Camera.cpp](https://github.com/gradzka/FaceRecognitionSystem/blob/master/FaceRecognitionSystem/FaceRecognitionSystem/Camera.cpp)  `sendMessage(char command)` procedure). It uses `CURL` to communication.

@gradzka I have tried this time with switch and been able to successfully ping with the camera IP. 
![Ping](https://user-images.githubusercontent.com/11074869/88707631-cf8d9380-d112-11ea-9723-e25e596ff17a.JPG)

Still, the problem remains. In your first comment, you said I should add the library from [https://github.com/linkingvision/rapidonvif/](https://github.com/linkingvision/rapidonvif/) I checked the library actually and tired to build their library for 64 bit windows. I could generate like this :
![generated_libraryfor64bit](https://user-images.githubusercontent.com/11074869/88707934-3ad76580-d113-11ea-9ac2-2ea3819080fd.JPG)
and finally linked the library and all to the visual studio project like this : 
![additional link library](https://user-images.githubusercontent.com/11074869/88708220-9dc8fc80-d113-11ea-89df-39302518d97b.JPG)
I couldn't build the **onvipcpp.lib** with your **openssl64**. So, I used from the [https://github.com/linkingvision/rapidonvif/tree/master/3rdparty/openssl-1.0.1g](https://github.com/linkingvision/rapidonvif/tree/master/3rdparty/openssl-1.0.1g). I am really confused about whether I built the library and created the project fine. Could you please share how you built the library for you? And Did I do something wrong while creating the project? I mean I don't understand why is it being too difficult for me to build/use the onvif library. 

Another thing is with your [https://github.com/gradzka/FaceRecognitionSystem](FaceRecognitionSystem) can I control my IP camera videos like set **fps** and **bit rate**? and get the video metadata? I also need to get the **mac address** of the camera.

**Comment by gradzka** [comment]
Hi, starting from the beginning, we've configured our project without `qt`, `database`, `opencv`, etc. as you mentioned.
So in your project directory should be only:
* `gsoap`
* `ONVIF`
* `onvifgen`
* `openssl-win64` - shouldn't be included in project, only copy it!

1. **Create** `Source.cpp`:

<pre>
#include "ONVIF/onvifclientdevice.hpp"
#include "ONVIF/onvifclientmedia.hpp"
#include <iostream>

int main(int argc, char** argv)
{
	string url = "http://192.168.1.67/onvif/device_service";
	string username = "username";
	string password = "password";
	OnvifClientDevice device(url, username, password);
	if (device.GetCapabilities() == 0)
	{
		OnvifClientMedia media(device);
		_trt__GetProfilesResponse profiles;
		media.GetProfiles(profiles);
		if (profiles.Profiles.size() > 0)
		{
			auto profileToken = profiles.Profiles[0]->token;
		}
	}
	return 0;
}
</pre>

2. **Change project properties**:

* Project> [Project Name] Properties > Debugging
Environment: `PATH=openssl-win64\lib%3b$(PATH)`
* C/C++ > General
Addictional Include Directories: `openssl-win64\include;onvifgen;gsoap\runtime;%(AdditionalIncludeDirectories)`
SDL checks: No
* C/C++ > Preprocessor
Preprocessor Definitions: `UNICODE;WIN32;WIN64;WITH_OPENSSL;WITH_DOM;WITH_PURE_VIRTUAL;WITH_NONAMESPACES;_DEBUG;_CONSOLE;%(PreprocessorDefinitions)`
* C/C++ > Code Generation
Basic Runtime Checks: `Default`
Runtime Library: `Multi-threaded Debug DLL (/MDd)`
* C/C++ > Language
Conformance mode: `No`
* C/C++ > Advanced
Compile As: `Compile as C++ Code (/TP)`
* Linker > General
Enable Incremental Linking: `Yes (/INCREMENTAL)`
Additional Library Dependencies: `openssl-win64\lib;%(AdditionalLibraryDirectories)`
* Linker > Input
Additional Dependencies: `libeay32.lib;ssleay32.lib;%(AdditionalDependencies)`

3. **Include in project all files except**:
* `mecevp.h` and `mecevp.cpp` from `gsoap>runtime`,
* `openssl-win64`

We've tested it on Platform x64 in Debgu configuration. For other configurations you should alse make changes. Perhaps not all changes are needed, but we're leaving that decision up to you.

Hope it helps!

**Comment by gradzka** [comment]
`Closed` due to no more comments
